In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
from scipy.linalg import toeplitz

#-----------------------------------
#Read from the file, find the entropy

colnames=['a'] 
#df = pd.read_csv("output.txt", names=colnames, header=None, dtype=str)
#df = pd.read_csv("output.txt", sep=" ", header=None)
df = pd.read_csv("rand1.txt", names=colnames, header=None, dtype=str) #Read the .txt file using pandas dataframe (=pd.DF)
print(df)

x = len(df.axes[0]) #Find the number of rows in the pd.DF, required for probability and entropy
print(x)

counts = df.value_counts() #Count the repitition/occurance (entries in rows) of each of the possible bit strings
#print(counts)

df2 = pd.DataFrame(counts, columns=list('a')) #Update pd.DF column with the rows being unique

prob = counts/x #Probability of each possible bit string
#print(prob)
df2['b'] = pd.DataFrame(prob) #Update pd.DF with prob as a new column of each row

df2['c'] = -(df2['b'] * np.log2(df2['b'])) #Find the entropy of the row elements and store in a new column
df3 = df2.sort_index() #Sort the rows with increasing bit string values
r_df3=len(df3.axes[0]) #Find the number of rows of the pd.DF 
c_df3=len(df3.axes[1]) #Find the number of columns of the pd.DF
print("rows=",r_df3,", cols=",c_df3)
#df3['0'] = df3['0'].apply('{:0>8}'.format)
#print(df2)
#print(df3)
total = (np.sum(df2['c'].values)) #Find the Shannon entropy (sum of individual entropies), required for hashing
print(total)

#df2["b"].plot()
#df3["b"].plot()
#plt.show()

#-----------------------------------
#Using the value of entropy, find the dimensionality of the required topelitz matrix and create one

#c_tmat=int(total*10)
c_tmat=int(total) #Find the floor of the entropy 
#r_tmat=120
r_tmat=int(input("Enter the size of list : ")) #Input the length of the bits from ADC

randomlist = []
for i in range(0,r_tmat):
    n = random.randint(0,1)
    randomlist.append(n)
print(randomlist) #Create a list of pseudo-random numbers (=PRN) of length equal to that of rows # of pd.DF, required for tmat

tmat_full=toeplitz(randomlist) #Create toeplitz matrix (=tmat) from the list of PRN
#print(tmat_full)
np.savetxt("toeplitz_mat_full.txt",tmat_full, delimiter=",", fmt='%s')

tmat=np.delete(tmat_full, np.s_[c_tmat:r_tmat], axis=1) #Reduce the size of tmat to the required quantity
print(tmat)
np.savetxt("toeplitz_mat.txt",tmat, delimiter=",", fmt='%s')

df_tmat = pd.DataFrame(tmat, index=None) #Create a DF of the reduced toeplitz matrix (=t.DF)
r_df_tmat=len(df_tmat.axes[0]) #Find the # of rows in the t.DF
c_df_tmat=len(df_tmat.axes[1]) #Find the # of columns in the t.DF
print("rows=",r_df_tmat,", cols=",c_df_tmat)
#print(df_tmat)

#-----------------------------------


      a
0  1100
1  1001
2  1011
3  1111
4  1001
5  0111
6  1101
7  0101
8  0100
9  1011
10
rows= 8 , cols= 3
2.9219280948873623
Enter the size of list : 4
[1, 0, 1, 1]
[[1 0]
 [0 1]
 [1 0]
 [1 1]]
rows= 4 , cols= 2


In [2]:
import pandas as pd
import numpy as np

result_list=[]

#-----------------------------------
#Multiply the 12-bit string list file with the toeplitz matrix to get reduced dimensionality matrix

#r_tmat=int(input("Enter the size of list : "))
r_df=int(x/8)
#print(r_df)
list_r_df=list(range(r_df))
#print(list_r_df)

df_split = np.array_split(df, r_df)
#df_split_list=df_split.values.tolist()
#print(df_split)

for y in list_r_df:
    list_df_split=(df_split[y]['a']).to_list()
    list_df_splitn=list(list_df_split)
    for i in list_df_splitn:
        list_final=list(i)
        list_final2=np.array(list_final)
        list_final3=pd.to_numeric(list_final2)
        matrix_multiply=np.matmul(list_final3, tmat)
        binary_matrix=np.mod(matrix_multiply,2)
        print(list_final3)
        #print(matrix_multiply)
        #print(binary_matrix)
        result_list.append(binary_matrix)

print(result_list)
np.savetxt("reduced_matrix.txt",result_list, delimiter=" ", fmt='%s')

#print(list_final2)

#for i in list_df_split0:
#    list_df_split=list(i)
#    print(list_df_split)

#for i in range(r_df):
#    ran_mat=np.matmul(df_split[i],df_tmat)
#    i=i+2

#df.drop(df.index[10:40], inplace=True)
#print(tmat_reduced)

#-----------------------------------
#join 10 lines in list and then perform matmul

row_merged = df.groupby(df.index//5).agg(list)
print(row_merged)


#-----------------------------------
#check for trimming first few bits in the 12 bit string



#-----------------------------------
#Find rnadomness using NIST suite of all the three quantities

[1 1 0 0]
[1 0 0 1]
[1 0 1 1]
[1 1 1 1]
[1 0 0 1]
[0 1 1 1]
[1 1 0 1]
[0 1 0 1]
[0 1 0 0]
[1 0 1 1]
[array([1, 1], dtype=int64), array([0, 1], dtype=int64), array([1, 1], dtype=int64), array([1, 0], dtype=int64), array([0, 1], dtype=int64), array([0, 0], dtype=int64), array([0, 0], dtype=int64), array([1, 0], dtype=int64), array([0, 1], dtype=int64), array([1, 1], dtype=int64)]
                                a
0  [1100, 1001, 1011, 1111, 1001]
1  [0111, 1101, 0101, 0100, 1011]


In [41]:
import pandas as pd

#r_df_list = []
#df.groupby(df.index // 5)

abbba=(df['a']).to_list()
print(abbba)
list_abbba=[]

for i in abbba:
    list_abbba=list(i)
    #print(list_abbba)

mat_1=list("1111")
print(mat_1)
numbers = pd.to_numeric(mat_1)
print(numbers)
mat_2 = ([1,0],[0,1],[1,0],[0,1])
print(mat_2)

res = np.dot(numbers,mat_2)
print(res)

s = df.groupby(df.index//5).agg(list)
print(s)
#s['liststring']=s.a.apply(lambda x: ', '.join(str(x)))
#s['liststring'] = s['a'].apply(lambda x: ','.join(map(str, x)))
#s['b']=s['a'].replace(',','')
s['b'] = s['a'].apply(lambda x: ''.join(map(str, x)))
#pd.s2 = s.apply(lambda x: x.str.replace(',', ''))
#s3=s2.a.apply(''.join)
print(s)

#len_merge = 3
#block = int(x/len_merge)
#df['block'] = np.repeat(range(1, block+1), n)
#print(df_block)

['1100', '1001', '1011', '1111', '1001', '0111', '1101', '0101', '0100', '1011']
['1', '1', '1', '1']
[1 1 1 1]
([1, 0], [0, 1], [1, 0], [0, 1])
[2 2]
                                a
0  [1100, 1001, 1011, 1111, 1001]
1  [0111, 1101, 0101, 0100, 1011]
                                a                     b
0  [1100, 1001, 1011, 1111, 1001]  11001001101111111001
1  [0111, 1101, 0101, 0100, 1011]  01111101010101001011
